export const GET_SEASONS_SUCCESS = 'GET_SEASONS_SUCCESS';
export const GET_SEASONS_START = 'GET_SEASONS_START';

export const GET_CHARACTER_IMG_START = 'GET_CHARACTER_IMG_START';
export const GET_CHARACTER_IMG_SUCCESS = 'GET_CHARACTER_IMG_SUCCESS';
